{
    "formatVersion": "1.1",
    "component": {
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-power-assert-runtime",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.5.1"
        }
    },
    "variants": [
        {
            "name": "androidNativeArm32ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "android_arm32"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-androidnativearm32/ArtifactsTest.version/kotlin-power-assert-runtime-androidnativearm32-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-androidnativearm32",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "androidNativeArm32SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "android_arm32"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-androidnativearm32/ArtifactsTest.version/kotlin-power-assert-runtime-androidnativearm32-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-androidnativearm32",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "androidNativeArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "android_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-androidnativearm64/ArtifactsTest.version/kotlin-power-assert-runtime-androidnativearm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-androidnativearm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "androidNativeArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "android_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-androidnativearm64/ArtifactsTest.version/kotlin-power-assert-runtime-androidnativearm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-androidnativearm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "androidNativeX64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "android_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-androidnativex64/ArtifactsTest.version/kotlin-power-assert-runtime-androidnativex64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-androidnativex64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "androidNativeX64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "android_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-androidnativex64/ArtifactsTest.version/kotlin-power-assert-runtime-androidnativex64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-androidnativex64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "androidNativeX86ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "android_x86"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-androidnativex86/ArtifactsTest.version/kotlin-power-assert-runtime-androidnativex86-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-androidnativex86",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "androidNativeX86SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "android_x86"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-androidnativex86/ArtifactsTest.version/kotlin-power-assert-runtime-androidnativex86-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-androidnativex86",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-iosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosArm64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-iosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-iosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosSimulatorArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-iossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosSimulatorArm64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-iossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosSimulatorArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-iossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosX64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iosx64/ArtifactsTest.version/kotlin-power-assert-runtime-iosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosX64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iosx64/ArtifactsTest.version/kotlin-power-assert-runtime-iosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "iosX64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "ios_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-iosx64/ArtifactsTest.version/kotlin-power-assert-runtime-iosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-iosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jsApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-js/ArtifactsTest.version/kotlin-power-assert-runtime-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jsRuntimeElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-js/ArtifactsTest.version/kotlin-power-assert-runtime-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jsSourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-js/ArtifactsTest.version/kotlin-power-assert-runtime-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jvmApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-jvm/ArtifactsTest.version/kotlin-power-assert-runtime-jvm-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-jvm",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jvmRuntimeElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-jvm/ArtifactsTest.version/kotlin-power-assert-runtime-jvm-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-jvm",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jvmSourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-jvm/ArtifactsTest.version/kotlin-power-assert-runtime-jvm-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-jvm",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "linuxArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "linux_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-linuxarm64/ArtifactsTest.version/kotlin-power-assert-runtime-linuxarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-linuxarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "linuxArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "linux_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-linuxarm64/ArtifactsTest.version/kotlin-power-assert-runtime-linuxarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-linuxarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "linuxX64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "linux_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-linuxx64/ArtifactsTest.version/kotlin-power-assert-runtime-linuxx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-linuxx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "linuxX64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "linux_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-linuxx64/ArtifactsTest.version/kotlin-power-assert-runtime-linuxx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-linuxx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "macosArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "macos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-macosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-macosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-macosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "macosArm64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "macos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-macosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-macosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-macosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "macosArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "macos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-macosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-macosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-macosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "macosX64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "macos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-macosx64/ArtifactsTest.version/kotlin-power-assert-runtime-macosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-macosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "macosX64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "macos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-macosx64/ArtifactsTest.version/kotlin-power-assert-runtime-macosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-macosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "macosX64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "macos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-macosx64/ArtifactsTest.version/kotlin-power-assert-runtime-macosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-macosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "metadataApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "common"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-power-assert-runtime-metadata-ArtifactsTest.version.jar",
                    "url": "kotlin-power-assert-runtime-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "metadataSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "common"
            },
            "files": [
                {
                    "name": "kotlin-power-assert-runtime-kotlin-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-power-assert-runtime-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "mingwX64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "mingw_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-mingwx64/ArtifactsTest.version/kotlin-power-assert-runtime-mingwx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-mingwx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "mingwX64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "mingw_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-mingwx64/ArtifactsTest.version/kotlin-power-assert-runtime-mingwx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-mingwx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-tvosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosArm64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-tvosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-tvosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosSimulatorArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-tvossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosSimulatorArm64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-tvossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosSimulatorArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-tvossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosX64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvosx64/ArtifactsTest.version/kotlin-power-assert-runtime-tvosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosX64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvosx64/ArtifactsTest.version/kotlin-power-assert-runtime-tvosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "tvosX64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "tvos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-tvosx64/ArtifactsTest.version/kotlin-power-assert-runtime-tvosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-tvosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmJsApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "js"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-wasm-js/ArtifactsTest.version/kotlin-power-assert-runtime-wasm-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-wasm-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmJsRuntimeElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "js"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-wasm-js/ArtifactsTest.version/kotlin-power-assert-runtime-wasm-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-wasm-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmJsSourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "js"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-wasm-js/ArtifactsTest.version/kotlin-power-assert-runtime-wasm-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-wasm-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmWasiApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-wasm-wasi/ArtifactsTest.version/kotlin-power-assert-runtime-wasm-wasi-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-wasm-wasi",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmWasiRuntimeElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-wasm-wasi/ArtifactsTest.version/kotlin-power-assert-runtime-wasm-wasi-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-wasm-wasi",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmWasiSourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-wasm-wasi/ArtifactsTest.version/kotlin-power-assert-runtime-wasm-wasi-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-wasm-wasi",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosArm32ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_arm32"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosarm32/ArtifactsTest.version/kotlin-power-assert-runtime-watchosarm32-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosarm32",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosArm32MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_arm32"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosarm32/ArtifactsTest.version/kotlin-power-assert-runtime-watchosarm32-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosarm32",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosArm32SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_arm32"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosarm32/ArtifactsTest.version/kotlin-power-assert-runtime-watchosarm32-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosarm32",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosArm64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosarm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosDeviceArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_device_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosdevicearm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosdevicearm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosdevicearm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosDeviceArm64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_device_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosdevicearm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosdevicearm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosdevicearm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosDeviceArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_device_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosdevicearm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosdevicearm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosdevicearm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosSimulatorArm64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosSimulatorArm64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosSimulatorArm64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchossimulatorarm64/ArtifactsTest.version/kotlin-power-assert-runtime-watchossimulatorarm64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchossimulatorarm64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosX64ApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosx64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosX64MetadataElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosx64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosx64",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "watchosX64SourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native",
                "org.jetbrains.kotlin.native.target": "watchos_x64"
            },
            "available-at": {
                "url": "../../kotlin-power-assert-runtime-watchosx64/ArtifactsTest.version/kotlin-power-assert-runtime-watchosx64-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-power-assert-runtime-watchosx64",
                "version": "ArtifactsTest.version"
            }
        }
    ]
}