{
    "formatVersion": "1.1",
    "component": {
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-gradle-plugin-api",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.0.0"
        }
    },
    "variants": [
        {
            "name": "apiElementsWithFixedAttribute",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "gradle811ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.11"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle811.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle811.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle811JavadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.11"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle811-javadoc.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle811-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle811RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.11"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle811.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle811.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle811SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.11"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle811-sources.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle811-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle813ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.13"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle813.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle813.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle813JavadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.13"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle813-javadoc.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle813-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle813RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.13"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle813.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle813.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle813SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.13"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle813-sources.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle813-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle81ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.1"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle81.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle81.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle81JavadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.1"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle81-javadoc.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle81-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle81RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.1"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle81.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle81.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle81SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.1"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle81-sources.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle81-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle82ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.2"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle82.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle82.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle82JavadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.2"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle82-javadoc.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle82-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle82RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.2"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle82.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle82.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle82SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.2"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle82-sources.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle82-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle85ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.5"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle85.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle85.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle85JavadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.5"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle85-javadoc.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle85-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle85RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.5"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle85.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle85.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle85SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.5"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle85-sources.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle85-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle86ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.6"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle86.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle86.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle86JavadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.6"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle86-javadoc.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle86-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle86RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.6"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle86.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle86.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle86SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.6"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle86-sources.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle86-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle88ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.8"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle88.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle88.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle88JavadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.8"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle88-javadoc.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle88-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle88RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "8.8"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle88.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle88.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle88SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "8.8"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle88-sources.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-gradle88-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-api",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "javadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-javadoc.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "runtimeElementsWithFixedAttribute",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-tools-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-util-klib"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "sourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-api-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-gradle-plugin-api-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        }
    ]
}