{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uklib-maven-gradle-packaging/1.0/uklib-maven-gradle-packaging-1.0.module",
    "group": "foo.bar",
    "module": "uklib-maven-gradle-packaging",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
      ],
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-linuxArm64Main-1.0.klib",
          "url": "uklib-maven-gradle-packaging-linuxarm64-1.0.klib",
          "size": 2921,
          "sha512": "c35fdf261bb63585c26f39a25e2323e3511a5a62c02932c7327be79fe5a6fba58274b321d4ae2d2295bef65dcbd0d747102a2eac00e9cf725da3f1f8f86c5d6d",
          "sha256": "af4eb4603e553a40161b41dbe76ef664e49a0a00ea42a540401ab48451165c05",
          "sha1": "f0a06fdfd35a8912c735fcf5245c62679c6aeee3",
          "md5": "cf46407fd807f658c4feea3cdf38c9ad"
        },
        {
          "name": "uklib-maven-gradle-packaging-linuxArm64Cinterop-fooMain-1.0.klib",
          "url": "uklib-maven-gradle-packaging-linuxarm64-1.0-cinterop-foo.klib",
          "size": 4473,
          "sha512": "04ae711a1dd2f0bcdf91aaea02d4a3426a10b3468a220496d5f8b87afa510713aa3bec7073d9cc4830508afb23ea74d51d1d8026395c349687fb392792283a8d",
          "sha256": "58b85d8a7623963ae8bd5495624ce71cdd68f92f95b4cf98f8b7c05fc263b1d5",
          "sha1": "686deadde8d82727862b3c4b9de3bc4a96edc31e",
          "md5": "9d91dcaa033225c5d138f4cb48411d8b"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-linuxarm64-1.0-sources.jar",
          "url": "uklib-maven-gradle-packaging-linuxarm64-1.0-sources.jar",
          "size": 479,
          "sha512": "686fd77f21ca2150e77e98fe3abb42871bc5ed26bb27e9be865c5aebe28bba09bb08dd4b1c5d127cce6b8d7eeefbfb64c86214ae3d332e7cfc70b32497358cd1",
          "sha256": "30af047fb16af81c8e78a5626ba0e0eb2d2afe7f7ea6bba0c823229bdfbdb0a2",
          "sha1": "2e05b1f02fbb2bbe1edd8e1d92a8912d2c0b6670",
          "md5": "f45f3fa2a7276ddd0cd618d7217d8884"
        }
      ]
    }
  ]
}
