{
    "formatVersion": "1.1",
    "component": {
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-gradle-plugin-idea",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "8.14"
        }
    },
    "variants": [
        {
            "name": "javadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-idea-ArtifactsTest.version-javadoc.jar",
                    "url": "kotlin-gradle-plugin-idea-ArtifactsTest.version-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "publishedCompile",
            "attributes": {
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ]
        },
        {
            "name": "publishedRuntime",
            "attributes": {
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ]
        },
        {
            "name": "runtimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-idea-ArtifactsTest.version.jar",
                    "url": "kotlin-gradle-plugin-idea-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "sourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-idea-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-gradle-plugin-idea-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "testFixturesApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-idea",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-idea-ArtifactsTest.version-test-fixtures.jar",
                    "url": "kotlin-gradle-plugin-idea-ArtifactsTest.version-test-fixtures.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-idea-test-fixtures",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "testFixturesRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-idea",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-idea-proto",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.21"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test",
                    "version": {
                        "requires": "2.1.21"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-idea-ArtifactsTest.version-test-fixtures.jar",
                    "url": "kotlin-gradle-plugin-idea-ArtifactsTest.version-test-fixtures.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin-idea-test-fixtures",
                    "version": "ArtifactsTest.version"
                }
            ]
        }
    ]
}
