{{- if ne (len .Values.configMapFromFiles.files) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  {{- range $file, $content := .Values.configMapFromFiles.files }}
  {{ $file | base }}: |-
{{ $content | indent 4 }}
  {{- end }}
{{- end }}
