apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.portMapping }}
    {{- range .Values.portMapping }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.servicePortMappings }}
    {{- range .Values.servicePortMappings }}
    - port: {{ .servicePort }}
      targetPort: {{ .podPort }}
      protocol: {{ .proto }} 
      name: {{ .name }}
    {{- end }}
    {{- end }}

  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
