#!/usr/bin/env bash

findScriptHome() {
    local source="${BASH_SOURCE[0]}"
    while [ -h "$source" ] ; do
	local linked="$(readlink "$source")"
	local dir="$(cd -P $(dirname "$source") && cd -P $(dirname "$linked") && pwd)"
	source="$dir/$(basename "$linked")"
    done
    (cd -P "$(dirname "$source")" && pwd)
}
SCRIPT_HOME="$(findScriptHome)"

PATH="$SCRIPT_HOME/../dist/bin:$PATH"

interop -Dkonan.dependencies="$SCRIPT_HOME/../dependencies/all" "$@"


