{
    "formatVersion": "1.1",
    "component": {
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-gradle-plugins-bom",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.2.1"
        }
    },
    "variants": [
        {
            "name": "apiElements",
            "attributes": {
                "org.gradle.category": "platform",
                "org.gradle.usage": "java-api"
            },
            "dependencyConstraints": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "atomicfu",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "compose-compiler-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "fus-statistics-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-allopen",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-assignment",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-dataframe",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-ecosystem-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-lombok",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-noarg",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-power-assert",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-sam-with-receiver",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-serialization",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ]
        },
        {
            "name": "runtimeElements",
            "attributes": {
                "org.gradle.category": "platform",
                "org.gradle.usage": "java-runtime"
            },
            "dependencyConstraints": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "atomicfu",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "compose-compiler-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "fus-statistics-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-allopen",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-assignment",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-dataframe",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-ecosystem-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-annotations",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-lombok",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-native-utils",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-noarg",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-power-assert",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-sam-with-receiver",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-serialization",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-tooling-core",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ]
        }
    ]
}