// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// DONT_TARGET_EXACT_BACKEND: WASM
// KJS_WITH_FULL_RUNTIME
// WITH_RUNTIME
import kotlin.test.*

fun box(): String {
    val uintList = mutableListOf<UInt>()
    for (i in 7u downTo 1u step 7) {
        uintList += i
    }
    assertEquals(listOf(7u), uintList)

    val ulongList = mutableListOf<ULong>()
    for (i in 7uL downTo 1uL step 7L) {
        ulongList += i
    }
    assertEquals(listOf(7uL), ulongList)

    return "OK"
}