/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.backend.jvm.lower.sequence.fusion.consumers

import org.jetbrains.kotlin.backend.jvm.JvmBackendContext
import org.jetbrains.kotlin.backend.jvm.lower.sequence.fusion.*
import org.jetbrains.kotlin.ir.IrElement
import org.jetbrains.kotlin.ir.builders.IrBuilderWithScope
import org.jetbrains.kotlin.ir.declarations.IrDeclarationParent
import org.jetbrains.kotlin.ir.declarations.IrVariable
import org.jetbrains.kotlin.ir.expressions.IrBlock
import org.jetbrains.kotlin.ir.expressions.IrBreak
import org.jetbrains.kotlin.ir.expressions.IrCall
import org.jetbrains.kotlin.ir.expressions.IrContinue
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.IrLoop
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.ir.visitors.transformChildrenVoid

private const val FOR_EACH = "forEach"
internal const val FIND = "find"
internal const val FIND_LAST = "findLast"
private const val FIRST = "first"
private const val FIRST_NOT_NULL_OF = "firstNotNullOf"
private const val FIRST_NOT_NULL_OF_OR_NULL = "firstNotNullOfOrNull"
private const val FIRST_OR_NULL = "firstOrNull"
private const val LAST = "last"
private const val LAST_OR_NULL = "lastOrNull"
private const val FILTER_TO = "filterTo"
private const val FILTER_NOT_TO = "filterNotTo"
private const val FILTER_NOT_NULL_TO = "filterNotNullTo"

/**
 * Each strategy has 3 parts:
 * 1. initialDeclarations - creates variables that will be used in the consumer body
 * 2. getConsumerBuilder - creates the consumer body dependent on the variable given by the producer/transformer
 * 3. createResult - creates the result of the producer body
 *
 * IR generated by getConsumerBuilder returns a Boolean to the producer/transformer.
 * If the Boolean is `false`, the producer/transformer will stop iterating over the sequence.
 */
internal abstract class ConsumerStrategy(val data: ConsumerData, val expression: IrExpression) {
    abstract fun getInitialDeclarations(): List<IrVariable>

    abstract fun getConsumerBuilder(): ConsumerBodyBuilder?

    abstract fun createResult(): IrExpression
}

internal fun ConsumerStrategy.createSequenceReplacement(): SequenceReplacement? =
    getConsumerBuilder()?.let { SequenceReplacement(getInitialDeclarations(), it, createResult()) }

internal data class ConsumerData(
    val context: JvmBackendContext,
    val builder: IrBuilderWithScope,
    val parent: IrDeclarationParent,
    val sequenceData: SequenceData,
)

internal fun createConsumerStrategy(
    expression: IrCall,
    functionName: String,
    data: ConsumerData,
): ConsumerStrategy? {
    return when (functionName) {
        FOR_EACH -> ForEachStrategy(data, expression)
        // find is equivalent to firstOrNull with a predicate argument
        FIND -> FirstLastStrategy(data, expression, isOrNull = true, isFirst = true)
        FIND_LAST -> FirstLastStrategy(data, expression, isOrNull = true, isFirst = false)
        FIRST -> FirstLastStrategy(data, expression, isOrNull = false, isFirst = true)
        FIRST_OR_NULL -> FirstLastStrategy(data, expression, isOrNull = true, isFirst = true)
        FIRST_NOT_NULL_OF -> FirstNotNullOfStrategy(data, expression, isOrNull = false)
        FIRST_NOT_NULL_OF_OR_NULL -> FirstNotNullOfStrategy(data, expression, isOrNull = true)
        LAST -> FirstLastStrategy(data, expression, isOrNull = false, isFirst = false)
        LAST_OR_NULL -> FirstLastStrategy(data, expression, isOrNull = true, isFirst = false)
        FILTER_TO -> FilterToStrategy(data, expression, FilterVersion.Filter)
        FILTER_NOT_TO -> FilterToStrategy(data, expression, FilterVersion.FilterNot)
        FILTER_NOT_NULL_TO -> FilterToStrategy(data, expression, FilterVersion.FilterNotNull)
        else -> null
    }
}

internal fun createConsumerStrategy(
    expression: IrBlock,
    data: ConsumerData,
): ConsumerStrategy? {
    val loopData = gatherLoopData(expression, data.parent, data.context) ?: return null
    return ForLoopStrategy(data, loopData, expression)
}

fun IrElement.rebindJumps(
    targetLoop: IrLoop,
    onBreak: (IrBreak) -> IrExpression,
    onContinue: (IrContinue) -> IrExpression
) = transformChildrenVoid(object : IrElementTransformerVoid() {
    override fun visitBreak(jump: IrBreak): IrExpression {
        if (jump.loop == targetLoop) return onBreak(jump)
        return super.visitBreak(jump)
    }

    override fun visitContinue(jump: IrContinue): IrExpression {
        if (jump.loop == targetLoop) return onContinue(jump)
        return super.visitContinue(jump)
    }
})
