package foo

// NOTE THIS FILE IS AUTO-GENERATED by the generateTestDataForReservedWords.kt. DO NOT EDIT!

object TestObject {
    fun private() { private() }

    fun test() {
        testNotRenamed("private", { ::private })
    }
}

fun box(): String {
    TestObject.test()

    return "OK"
}