package foo

// NOTE THIS FILE IS AUTO-GENERATED by the generateTestDataForReservedWords.kt. DO NOT EDIT!

object TestObject {
    fun `try`() { `try`() }

    fun test() {
        testNotRenamed("try", { ::`try` })
    }
}

fun box(): String {
    TestObject.test()

    return "OK"
}