package foo

// NOTE THIS FILE IS AUTO-GENERATED by the generateTestDataForReservedWords.kt. DO NOT EDIT!

trait export { class object {} }

fun box(): String {
    testNotRenamed("export", { export })

    return "OK"
}