package foo

// NOTE THIS FILE IS AUTO-GENERATED by the generateTestDataForReservedWords.kt. DO NOT EDIT!

class `this` { class object {} }

fun box(): String {
    testNotRenamed("this", { `this` })

    return "OK"
}