namespace org.w3c.fullscreen;


// Downloaded from https://raw.githubusercontent.com/whatwg/fullscreen/master/Overview.src.html
partial interface Element {
  void requestFullscreen();
};

partial interface Document {
  readonly attribute boolean fullscreenEnabled;
  readonly attribute Element? fullscreenElement;

  void exitFullscreen();

  attribute EventHandler onfullscreenchange;
  attribute EventHandler onfullscreenerror;
};

