/*
 * Copyright 2010-2020 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.test.model

import org.jetbrains.kotlin.test.TargetBackend
import org.jetbrains.kotlin.test.backend.ir.IrBackendInput
import org.jetbrains.kotlin.test.frontend.classic.ClassicFrontendOutputArtifact
import org.jetbrains.kotlin.test.frontend.fir.FirOutputArtifact
import org.jetbrains.kotlin.test.services.CompilationStage

object FrontendKinds {
    object ClassicFrontend : FrontendKind<ClassicFrontendOutputArtifact>("ClassicFrontend")
    object FIR : FrontendKind<FirOutputArtifact>("FIR")

    fun fromString(string: String): FrontendKind<*>? {
        return when (string) {
            "ClassicFrontend" -> ClassicFrontend
            "FIR" -> FIR
            else -> null
        }
    }
}

object BackendKinds {
    /**
     * The artifact kind representing IR generated by the frontend.
     */
    object IrBackend : BackendKind<IrBackendInput>("IrBackend")

    fun fromTargetBackend(targetBackend: TargetBackend?): BackendKind<*> = when {
        targetBackend == null -> BackendKind.NoBackend
        targetBackend.isIR -> IrBackend
        else -> error("Unsupported backend kind: $targetBackend")
    }
}

object ArtifactKinds {
    object Jvm : ArtifactKind<BinaryArtifacts.Jvm>("JVM", CompilationStage.FIRST)
    object Js : ArtifactKind<BinaryArtifacts.Js>("JS", CompilationStage.SECOND)
    object Native : ArtifactKind<BinaryArtifacts.Native>("Native", CompilationStage.SECOND)
    object Wasm : ArtifactKind<BinaryArtifacts.Wasm>("Wasm", CompilationStage.SECOND)
    object KLib : ArtifactKind<BinaryArtifacts.KLib>("KLib", CompilationStage.FIRST)

    fun fromString(string: String): ArtifactKind<*>? {
        return when (string) {
            "Jvm" -> Jvm
            "Js" -> Js
            "Native" -> Native
            "Wasm" -> Wasm
            "KLib" -> KLib
            else -> null
        }
    }
}
