package kotlin.native.internal

class IntrinsicType {
    companion object {
        const val PLUS                  = "PLUS"
        const val MINUS                 = "MINUS"
        const val TIMES                 = "TIMES"
        const val SIGNED_DIV            = "SIGNED_DIV"
        const val SIGNED_REM            = "SIGNED_REM"
        const val UNSIGNED_DIV          = "UNSIGNED_DIV"
        const val UNSIGNED_REM          = "UNSIGNED_REM"
        const val INC                   = "INC"
        const val DEC                   = "DEC"
        const val UNARY_PLUS            = "UNARY_PLUS"
        const val UNARY_MINUS           = "UNARY_MINUS"
        const val SHL                   = "SHL"
        const val SHR                   = "SHR"
        const val USHR                  = "USHR"
        const val AND                   = "AND"
        const val OR                    = "OR"
        const val XOR                   = "XOR"
        const val INV                   = "INV"
        const val SIGN_EXTEND           = "SIGN_EXTEND"
        const val ZERO_EXTEND           = "ZERO_EXTEND"
        const val INT_TRUNCATE          = "INT_TRUNCATE"
        const val FLOAT_TRUNCATE        = "FLOAT_TRUNCATE"
        const val FLOAT_EXTEND          = "FLOAT_EXTEND"
        const val SIGNED_TO_FLOAT       = "SIGNED_TO_FLOAT"
        const val UNSIGNED_TO_FLOAT     = "UNSIGNED_TO_FLOAT"
        const val FLOAT_TO_SIGNED       = "FLOAT_TO_SIGNED"
        const val SIGNED_COMPARE_TO     = "SIGNED_COMPARE_TO"
        const val UNSIGNED_COMPARE_TO   = "UNSIGNED_COMPARE_TO"
        const val NOT                   = "NOT"
        const val TO_BITS               = "TO_BITS"
        const val FROM_BITS             = "FROM_BITS"
    }
}