plugins {
    id "org.jetbrains.kotlin.jvm"
    id "org.jetbrains.kotlin.kapt"
}

kotlin.jvmToolchain(8)

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation project(":annotation-processor")
    kapt project(":annotation-processor")
    kotlinCompilerPluginClasspath project(":plugin")
}
