{
    "formatVersion": "1.1",
    "component": {
        "url": "../../kotlin-stdlib/ArtifactsTest.version/kotlin-stdlib-ArtifactsTest.version.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.1.0"
        }
    },
    "variants": [
        {
            "name": "wasmWasiApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.klib.packaging": "packed",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "files": [
                {
                    "name": "kotlin-stdlib-wasm-wasi-ArtifactsTest.version.klib",
                    "url": "kotlin-stdlib-wasm-wasi-ArtifactsTest.version.klib",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "wasmWasiRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.klib.packaging": "packed",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "files": [
                {
                    "name": "kotlin-stdlib-wasm-wasi-ArtifactsTest.version.klib",
                    "url": "kotlin-stdlib-wasm-wasi-ArtifactsTest.version.klib",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "wasmWasiSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "files": [
                {
                    "name": "kotlin-stdlib-wasm-wasi-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-stdlib-wasm-wasi-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        }
    ]
}