// GENERATED build.gradle.kts
// GENERATED BY kotlin.project-wizard.core.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompileJar("intellijDep(), { includeJars("util") }")
    jpsLikeCompileJar("intellijDep(), { includeJars("intellij-core") }")
    jpsLikeCompileJar("intellijDep(), { includeJars("intellij-core-analysis-deprecated") }")
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()