{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uklib-maven-gradle-packaging/1.0/uklib-maven-gradle-packaging-1.0.module",
    "group": "foo.bar",
    "module": "uklib-maven-gradle-packaging",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
      ],
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-js-1.0.klib",
          "url": "uklib-maven-gradle-packaging-js-1.0.klib",
          "size": 2513,
          "sha512": "374c9dc240d365fc0ccad6a3af7e98b7bbcc77d545104c0f6ebc46d5041e545ad9c4489404339649926314ae45aa3b062969a5cd37ba04fa44a2ed67dc7293e8",
          "sha256": "e230fcfaae3cc0bd7cf23e4fa83aa117c3a7acb3c0f15687db1fd9679c3c7233",
          "sha1": "d145161f6aebe767628f182d2c386985056c9a72",
          "md5": "a1d4b46cf31a0359f5f1d41c4970831a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
      ],
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-js-1.0.klib",
          "url": "uklib-maven-gradle-packaging-js-1.0.klib",
          "size": 2513,
          "sha512": "374c9dc240d365fc0ccad6a3af7e98b7bbcc77d545104c0f6ebc46d5041e545ad9c4489404339649926314ae45aa3b062969a5cd37ba04fa44a2ed67dc7293e8",
          "sha256": "e230fcfaae3cc0bd7cf23e4fa83aa117c3a7acb3c0f15687db1fd9679c3c7233",
          "sha1": "d145161f6aebe767628f182d2c386985056c9a72",
          "md5": "a1d4b46cf31a0359f5f1d41c4970831a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-js-1.0-sources.jar",
          "url": "uklib-maven-gradle-packaging-js-1.0-sources.jar",
          "size": 479,
          "sha512": "686fd77f21ca2150e77e98fe3abb42871bc5ed26bb27e9be865c5aebe28bba09bb08dd4b1c5d127cce6b8d7eeefbfb64c86214ae3d332e7cfc70b32497358cd1",
          "sha256": "30af047fb16af81c8e78a5626ba0e0eb2d2afe7f7ea6bba0c823229bdfbdb0a2",
          "sha1": "2e05b1f02fbb2bbe1edd8e1d92a8912d2c0b6670",
          "md5": "f45f3fa2a7276ddd0cd618d7217d8884"
        }
      ]
    }
  ]
}
