// Copyright (c) 2011, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

package com.google.dart.compiler.backend.js.ast;

enum NodeKind {
    ARRAY_ACCESS,
    ARRAY,
    BINARY_OP,
    BLOCK,
    BOOLEAN,
    BREAK,
    CASE,
    CATCH,
    CONDITIONAL,
    CONTINUE,
    DEBUGGER,
    DEFAULT,
    DO,
    EMPTY,
    EXPRESSION_STMT,
    FOR,
    FOR_IN,
    FUNCTION,
    IF,
    INVOKE,
    LABEL,
    NAME_REF,
    NEW,
    NULL,
    NUMBER,
    OBJECT,
    PARAMETER,
    POSTFIX_OP,
    PREFIX_OP,
    PROGRAM,
    PROGRAM_FRAGMENT,
    PROPERTY_INIT,
    REGEXP,
    RETURN,
    STRING,
    SWITCH,
    THIS,
    THROW,
    TRY,
    VARS,
    VAR,
    WHILE
}
