plugins {
    id("common-configuration")
    id("test-federation-convention")
    id("com.autonomousapps.dependency-analysis")
    id("org.jetbrains.kotlin.jvm")
}

description = 'Kotlin annotations for JVM'

JvmToolchain.configureJvmToolchain(project, JdkMajorVersion.JDK_1_8)

RepoArtifacts.publish(project)

sourceSets {
    main {
        java {
            srcDir 'src'
        }
    }
}

RepoArtifacts.sourcesJar(project)
RepoArtifacts.javadocJar(project)

compileKotlin {
    compilerOptions.freeCompilerArgs = [
            "-Xallow-kotlin-package",
    ]
    compilerOptions.moduleName = project.name
}
