package org.jetbrains.kotlin.gradle.plugin.mpp.pm20

import org.gradle.api.artifacts.Configuration
import org.jetbrains.kotlin.konan.target.KonanTarget
import javax.inject.Inject

// DO NOT EDIT MANUALLY! Generated by org.jetbrains.kotlin.generators.gradle.dsl.KpmNativeVariantCodegenKt
abstract class GradleKpmAndroidNativeX64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.ANDROID_X64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.ANDROID_X64,
            GradleKpmAndroidNativeX64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmAndroidNativeX64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmAndroidNativeX86Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.ANDROID_X86,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.ANDROID_X86,
            GradleKpmAndroidNativeX86Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmAndroidNativeX86Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmAndroidNativeArm32Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.ANDROID_ARM32,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.ANDROID_ARM32,
            GradleKpmAndroidNativeArm32Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmAndroidNativeArm32Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmAndroidNativeArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.ANDROID_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.ANDROID_ARM64,
            GradleKpmAndroidNativeArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmAndroidNativeArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmIosArm32Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.IOS_ARM32,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.IOS_ARM32,
            GradleKpmIosArm32Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmIosArm32Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmIosArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.IOS_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.IOS_ARM64,
            GradleKpmIosArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmIosArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmIosX64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.IOS_X64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.IOS_X64,
            GradleKpmIosX64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmIosX64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmIosSimulatorArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.IOS_SIMULATOR_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.IOS_SIMULATOR_ARM64,
            GradleKpmIosSimulatorArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmIosSimulatorArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmWatchosArm32Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.WATCHOS_ARM32,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.WATCHOS_ARM32,
            GradleKpmWatchosArm32Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmWatchosArm32Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmWatchosArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.WATCHOS_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.WATCHOS_ARM64,
            GradleKpmWatchosArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmWatchosArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmWatchosX86Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.WATCHOS_X86,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.WATCHOS_X86,
            GradleKpmWatchosX86Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmWatchosX86Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmWatchosX64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.WATCHOS_X64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.WATCHOS_X64,
            GradleKpmWatchosX64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmWatchosX64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmWatchosSimulatorArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.WATCHOS_SIMULATOR_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.WATCHOS_SIMULATOR_ARM64,
            GradleKpmWatchosSimulatorArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmWatchosSimulatorArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmWatchosDeviceArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.WATCHOS_DEVICE_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.WATCHOS_DEVICE_ARM64,
            GradleKpmWatchosDeviceArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmWatchosDeviceArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmTvosArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.TVOS_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.TVOS_ARM64,
            GradleKpmTvosArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmTvosArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmTvosX64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.TVOS_X64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.TVOS_X64,
            GradleKpmTvosX64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmTvosX64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmTvosSimulatorArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.TVOS_SIMULATOR_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.TVOS_SIMULATOR_ARM64,
            GradleKpmTvosSimulatorArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmTvosSimulatorArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmLinuxX64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.LINUX_X64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.LINUX_X64,
            GradleKpmLinuxX64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmLinuxX64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmMingwX86Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.MINGW_X86,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.MINGW_X86,
            GradleKpmMingwX86Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmMingwX86Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmMingwX64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.MINGW_X64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.MINGW_X64,
            GradleKpmMingwX64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmMingwX64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmMacosX64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.MACOS_X64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.MACOS_X64,
            GradleKpmMacosX64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmMacosX64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmMacosArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.MACOS_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.MACOS_ARM64,
            GradleKpmMacosArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmMacosArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmLinuxArm64Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.LINUX_ARM64,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.LINUX_ARM64,
            GradleKpmLinuxArm64Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmLinuxArm64Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmLinuxArm32HfpVariant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.LINUX_ARM32_HFP,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.LINUX_ARM32_HFP,
            GradleKpmLinuxArm32HfpVariant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmLinuxArm32HfpVariant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmLinuxMips32Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.LINUX_MIPS32,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.LINUX_MIPS32,
            GradleKpmLinuxMips32Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmLinuxMips32Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmLinuxMipsel32Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.LINUX_MIPSEL32,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.LINUX_MIPSEL32,
            GradleKpmLinuxMipsel32Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmLinuxMipsel32Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

abstract class GradleKpmWasm32Variant @Inject constructor(
    containingModule: GradleKpmModule,
    fragmentName: String,
    dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
    compileDependencyConfiguration: Configuration,
    apiElementsConfiguration: Configuration,
    hostSpecificMetadataElementsConfiguration: Configuration?
) : GradleKpmNativeVariantInternal(
    containingModule = containingModule,
    fragmentName = fragmentName,
    konanTarget = KonanTarget.WASM32,
    dependencyConfigurations = dependencyConfigurations,
    compileDependencyConfiguration = compileDependencyConfiguration,
    apiElementsConfiguration = apiElementsConfiguration,
    hostSpecificMetadataElementsConfiguration = hostSpecificMetadataElementsConfiguration
) {
    companion object {
        val constructor = GradleKpmNativeVariantConstructor(
            KonanTarget.WASM32,
            GradleKpmWasm32Variant::class.java
        ) { containingModule: GradleKpmModule,
            fragmentName: String,
            dependencyConfigurations: GradleKpmFragmentDependencyConfigurations,
            compileDependencyConfiguration: Configuration,
            apiElementsConfiguration: Configuration,
            hostSpecificMetadataElementsConfiguration: Configuration? ->
            containingModule.project.objects.newInstance(
                GradleKpmWasm32Variant::class.java,
                containingModule,
                fragmentName,
                dependencyConfigurations,
                compileDependencyConfiguration,
                apiElementsConfiguration,
                hostSpecificMetadataElementsConfiguration
            )
        }
    }
}

internal val allKpmNativeVariantConstructors = listOf(
    GradleKpmAndroidNativeX64Variant.constructor,
    GradleKpmAndroidNativeX86Variant.constructor,
    GradleKpmAndroidNativeArm32Variant.constructor,
    GradleKpmAndroidNativeArm64Variant.constructor,
    GradleKpmIosArm32Variant.constructor,
    GradleKpmIosArm64Variant.constructor,
    GradleKpmIosX64Variant.constructor,
    GradleKpmIosSimulatorArm64Variant.constructor,
    GradleKpmWatchosArm32Variant.constructor,
    GradleKpmWatchosArm64Variant.constructor,
    GradleKpmWatchosX86Variant.constructor,
    GradleKpmWatchosX64Variant.constructor,
    GradleKpmWatchosSimulatorArm64Variant.constructor,
    GradleKpmWatchosDeviceArm64Variant.constructor,
    GradleKpmTvosArm64Variant.constructor,
    GradleKpmTvosX64Variant.constructor,
    GradleKpmTvosSimulatorArm64Variant.constructor,
    GradleKpmLinuxX64Variant.constructor,
    GradleKpmMingwX86Variant.constructor,
    GradleKpmMingwX64Variant.constructor,
    GradleKpmMacosX64Variant.constructor,
    GradleKpmMacosArm64Variant.constructor,
    GradleKpmLinuxArm64Variant.constructor,
    GradleKpmLinuxArm32HfpVariant.constructor,
    GradleKpmLinuxMips32Variant.constructor,
    GradleKpmLinuxMipsel32Variant.constructor,
    GradleKpmWasm32Variant.constructor
)

internal fun kpmNativeVariantClass(konanTarget: KonanTarget): Class<out GradleKpmNativeVariantInternal>? = when (konanTarget) {
    KonanTarget.ANDROID_X64 -> GradleKpmAndroidNativeX64Variant::class.java
    KonanTarget.ANDROID_X86 -> GradleKpmAndroidNativeX86Variant::class.java
    KonanTarget.ANDROID_ARM32 -> GradleKpmAndroidNativeArm32Variant::class.java
    KonanTarget.ANDROID_ARM64 -> GradleKpmAndroidNativeArm64Variant::class.java
    KonanTarget.IOS_ARM32 -> GradleKpmIosArm32Variant::class.java
    KonanTarget.IOS_ARM64 -> GradleKpmIosArm64Variant::class.java
    KonanTarget.IOS_X64 -> GradleKpmIosX64Variant::class.java
    KonanTarget.IOS_SIMULATOR_ARM64 -> GradleKpmIosSimulatorArm64Variant::class.java
    KonanTarget.WATCHOS_ARM32 -> GradleKpmWatchosArm32Variant::class.java
    KonanTarget.WATCHOS_ARM64 -> GradleKpmWatchosArm64Variant::class.java
    KonanTarget.WATCHOS_X86 -> GradleKpmWatchosX86Variant::class.java
    KonanTarget.WATCHOS_X64 -> GradleKpmWatchosX64Variant::class.java
    KonanTarget.WATCHOS_SIMULATOR_ARM64 -> GradleKpmWatchosSimulatorArm64Variant::class.java
    KonanTarget.WATCHOS_DEVICE_ARM64 -> GradleKpmWatchosDeviceArm64Variant::class.java
    KonanTarget.TVOS_ARM64 -> GradleKpmTvosArm64Variant::class.java
    KonanTarget.TVOS_X64 -> GradleKpmTvosX64Variant::class.java
    KonanTarget.TVOS_SIMULATOR_ARM64 -> GradleKpmTvosSimulatorArm64Variant::class.java
    KonanTarget.LINUX_X64 -> GradleKpmLinuxX64Variant::class.java
    KonanTarget.MINGW_X86 -> GradleKpmMingwX86Variant::class.java
    KonanTarget.MINGW_X64 -> GradleKpmMingwX64Variant::class.java
    KonanTarget.MACOS_X64 -> GradleKpmMacosX64Variant::class.java
    KonanTarget.MACOS_ARM64 -> GradleKpmMacosArm64Variant::class.java
    KonanTarget.LINUX_ARM64 -> GradleKpmLinuxArm64Variant::class.java
    KonanTarget.LINUX_ARM32_HFP -> GradleKpmLinuxArm32HfpVariant::class.java
    KonanTarget.LINUX_MIPS32 -> GradleKpmLinuxMips32Variant::class.java
    KonanTarget.LINUX_MIPSEL32 -> GradleKpmLinuxMipsel32Variant::class.java
    KonanTarget.WASM32 -> GradleKpmWasm32Variant::class.java
    else -> null
}