#!/usr/bin/env bash
#
# Copyright 2010-2017 JetBrains s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TOOL_NAME="$1"
shift

if [ -z "$JAVACMD" -a -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD=java
fi
[ -n "$JAVACMD" ] || JAVACMD=java

findJavaVersion() {
    # Note that this only loads the first component of the version, so "1.8.0_265" -> "1".
    # But it's fine because major version is 9 for JDK 9, and so on.
    regex='^.*version "([[:digit:]]+).*$'
    while read -r line; do
        if [[ "$line" =~ $regex ]]; then
            echo ${BASH_REMATCH[1]}
        fi
    done <<< $("${JAVACMD:=java}" -version 2>&1)
}

declare -a java_args
declare -a java_opts
declare -a konan_args

while [ $# -gt 0 ]; do
  case "$1" in
    -D*)
      java_args=("${java_args[@]}" "$1")
      shift
      ;;
    -J*)
      java_args=("${java_args[@]}" "${1:2}")
      shift
      ;;
    --time)
      konan_args=("${konan_args[@]}" --time)
      java_args=("${java_args[@]}" -Dkonan.profile=true)
      TIMECMD=time
      shift
      ;;
     *)
      konan_args[${#konan_args[@]}]=$1
      shift
      ;;
  esac
done

findHome() {
    local source="${BASH_SOURCE[0]}"
    while [ -h "$source" ] ; do
        local linked="$(readlink "$source")"
        local dir="$(cd -P $(dirname "$source") && cd -P $(dirname "$linked") && pwd)"
        source="$dir/$(basename "$linked")"
    done
    (cd -P "$(dirname "$source")/.." && pwd)
}
KONAN_HOME="$(findHome)"

java_version="$(findJavaVersion)"

if [[ $java_version -ge 24 ]]; then
    # Allow JNI access for all compiler code. In particular, this is needed for jansi (see `PlainTextMessageRenderer`).
    java_args=("${java_args[@]}" "--enable-native-access=ALL-UNNAMED")

    # Suppress unsafe deprecation warnings, see KT-76799 and IDEA-370928.
    java_args=("${java_args[@]}" "--sun-misc-unsafe-memory-access=allow")
fi

java_opts=(-ea \
            -Xmx3G \
            -XX:TieredStopAtLevel=1 \
            -Dfile.encoding=UTF-8 \
            -Dkonan.home="$KONAN_HOME" \
            ${JAVA_OPTS})

# Unset some environment variables which are set by XCode and may potentially affect the tool executed.
while IFS=$'\r' read -r line || [[ -n "$line" ]]; do
    unset $line
done < "${KONAN_HOME}/tools/env_blacklist"

KONAN_JAR="${KONAN_HOME}/konan/lib/kotlin-native-compiler-embeddable.jar"
KONAN_CLASSPATH="$KONAN_JAR"
TOOL_CLASS=org.jetbrains.kotlin.cli.utilities.MainKt
LIBCLANG_DISABLE_CRASH_RECOVERY=1 \
$TIMECMD "$JAVACMD" "${java_opts[@]}" "${java_args[@]}" -cp "$KONAN_CLASSPATH" "$TOOL_CLASS" "$TOOL_NAME" "${konan_args[@]}"

