{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uklib-maven-gradle-packaging/1.0/uklib-maven-gradle-packaging-1.0.module",
    "group": "foo.bar",
    "module": "uklib-maven-gradle-packaging",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
      ],
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-wasm-wasi-1.0.klib",
          "url": "uklib-maven-gradle-packaging-wasm-wasi-1.0.klib",
          "size": 2505,
          "sha512": "11a3b46443f453205bd70f33644fae3978754a0cbb317f6af5e1f4fd27edb04144bca82ca826f0cc059d318d5fcc99227100f6f6cb6f51b200fc68d067faf6d7",
          "sha256": "eed5e2a5609abbf77f1a60ab24d2f760d3f9e93efa2cbf2b7b14d6d502a42986",
          "sha1": "aa04a1b1aa80daa291ab279bbf64208e686cfc79",
          "md5": "0ecfa732c15f905be4443d4587e32dd7"
        }
      ]
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
      ],
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-wasm-wasi-1.0.klib",
          "url": "uklib-maven-gradle-packaging-wasm-wasi-1.0.klib",
          "size": 2505,
          "sha512": "11a3b46443f453205bd70f33644fae3978754a0cbb317f6af5e1f4fd27edb04144bca82ca826f0cc059d318d5fcc99227100f6f6cb6f51b200fc68d067faf6d7",
          "sha256": "eed5e2a5609abbf77f1a60ab24d2f760d3f9e93efa2cbf2b7b14d6d502a42986",
          "sha1": "aa04a1b1aa80daa291ab279bbf64208e686cfc79",
          "md5": "0ecfa732c15f905be4443d4587e32dd7"
        }
      ]
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-wasm-wasi-1.0-sources.jar",
          "url": "uklib-maven-gradle-packaging-wasm-wasi-1.0-sources.jar",
          "size": 479,
          "sha512": "686fd77f21ca2150e77e98fe3abb42871bc5ed26bb27e9be865c5aebe28bba09bb08dd4b1c5d127cce6b8d7eeefbfb64c86214ae3d332e7cfc70b32497358cd1",
          "sha256": "30af047fb16af81c8e78a5626ba0e0eb2d2afe7f7ea6bba0c823229bdfbdb0a2",
          "sha1": "2e05b1f02fbb2bbe1edd8e1d92a8912d2c0b6670",
          "md5": "f45f3fa2a7276ddd0cd618d7217d8884"
        }
      ]
    }
  ]
}
