/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlinx.serialization.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlinx.serialization.GenerateSerializationTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
public class LLSerializationBlackBoxTestGenerated extends AbstractLLSerializationBlackBoxTest {
  @Nested
  @TestMetadata("plugins/kotlinx-serialization/testData/boxIr")
  @TestDataPath("$PROJECT_ROOT")
  public class BoxIr {
    private void run(String fileName) {
      runTest("plugins/kotlinx-serialization/testData/boxIr/" + fileName);
    }

    @Test
    @TestMetadata("allConstructorsAccessible.kt")
    public void testAllConstructorsAccessible() {
      run("allConstructorsAccessible.kt");
    }

    @Test
    public void testAllFilesPresentInBoxIr() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("plugins/kotlinx-serialization/testData/boxIr"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("annotationsOnFile.kt")
    public void testAnnotationsOnFile() {
      run("annotationsOnFile.kt");
    }

    @Test
    @TestMetadata("annotationsOnFileExplicitArray.kt")
    public void testAnnotationsOnFileExplicitArray() {
      run("annotationsOnFileExplicitArray.kt");
    }

    @Test
    @TestMetadata("caching.kt")
    public void testCaching() {
      run("caching.kt");
    }

    @Test
    @TestMetadata("clashBetweenSerializableAndNonSerializableProperty.kt")
    public void testClashBetweenSerializableAndNonSerializableProperty() {
      run("clashBetweenSerializableAndNonSerializableProperty.kt");
    }

    @Test
    @TestMetadata("classSerializerAsObject.kt")
    public void testClassSerializerAsObject() {
      run("classSerializerAsObject.kt");
    }

    @Test
    @TestMetadata("constValInSerialName.kt")
    public void testConstValInSerialName() {
      run("constValInSerialName.kt");
    }

    @Test
    @TestMetadata("contextualByDefault.kt")
    public void testContextualByDefault() {
      run("contextualByDefault.kt");
    }

    @Test
    @TestMetadata("contextualFallback.kt")
    public void testContextualFallback() {
      run("contextualFallback.kt");
    }

    @Test
    @TestMetadata("contextualWithTypeParameters.kt")
    public void testContextualWithTypeParameters() {
      run("contextualWithTypeParameters.kt");
    }

    @Test
    @TestMetadata("customFixedNonSerializableArguments.kt")
    public void testCustomFixedNonSerializableArguments() {
      run("customFixedNonSerializableArguments.kt");
    }

    @Test
    @TestMetadata("delegatedInterface.kt")
    public void testDelegatedInterface() {
      run("delegatedInterface.kt");
    }

    @Test
    @TestMetadata("delegatedProperty.kt")
    public void testDelegatedProperty() {
      run("delegatedProperty.kt");
    }

    @Test
    @TestMetadata("enumsAreCached.kt")
    public void testEnumsAreCached() {
      run("enumsAreCached.kt");
    }

    @Test
    @TestMetadata("excludedFromExport.kt")
    public void testExcludedFromExport() {
      run("excludedFromExport.kt");
    }

    @Test
    @TestMetadata("excludedFromFileExport.kt")
    public void testExcludedFromFileExport() {
      run("excludedFromFileExport.kt");
    }

    @Test
    @TestMetadata("expectActual.kt")
    public void testExpectActual() {
      run("expectActual.kt");
    }

    @Test
    @TestMetadata("expectActualSealedClass.kt")
    public void testExpectActualSealedClass() {
      run("expectActualSealedClass.kt");
    }

    @Test
    @TestMetadata("externalSerialierJava.kt")
    public void testExternalSerialierJava() {
      run("externalSerialierJava.kt");
    }

    @Test
    @TestMetadata("externalSerializerForClassWithNonSerializableType.kt")
    public void testExternalSerializerForClassWithNonSerializableType() {
      run("externalSerializerForClassWithNonSerializableType.kt");
    }

    @Test
    @TestMetadata("generatedClassifiersViaLibraryDependency.kt")
    public void testGeneratedClassifiersViaLibraryDependency() {
      run("generatedClassifiersViaLibraryDependency.kt");
    }

    @Test
    @TestMetadata("genericBaseClassMultiple.kt")
    public void testGenericBaseClassMultiple() {
      run("genericBaseClassMultiple.kt");
    }

    @Test
    @TestMetadata("genericBaseClassSimple.kt")
    public void testGenericBaseClassSimple() {
      run("genericBaseClassSimple.kt");
    }

    @Test
    @TestMetadata("generics.kt")
    public void testGenerics() {
      run("generics.kt");
    }

    @Test
    @TestMetadata("inlineClasses.kt")
    public void testInlineClasses() {
      run("inlineClasses.kt");
    }

    @Test
    @TestMetadata("instantSerializer.kt")
    public void testInstantSerializer() {
      run("instantSerializer.kt");
    }

    @Test
    @TestMetadata("interfaces.kt")
    public void testInterfaces() {
      run("interfaces.kt");
    }

    @Test
    @TestMetadata("intrinsicAnnotations.kt")
    public void testIntrinsicAnnotations() {
      run("intrinsicAnnotations.kt");
    }

    @Test
    @TestMetadata("intrinsicsBox.kt")
    public void testIntrinsicsBox() {
      run("intrinsicsBox.kt");
    }

    @Test
    @TestMetadata("intrinsicsConsistency.kt")
    public void testIntrinsicsConsistency() {
      run("intrinsicsConsistency.kt");
    }

    @Test
    @TestMetadata("intrinsicsNonReified.kt")
    public void testIntrinsicsNonReified() {
      run("intrinsicsNonReified.kt");
    }

    @Test
    @TestMetadata("intrinsicsNullable.kt")
    public void testIntrinsicsNullable() {
      run("intrinsicsNullable.kt");
    }

    @Test
    @TestMetadata("intrinsicsPolymorphicPriority.kt")
    public void testIntrinsicsPolymorphicPriority() {
      run("intrinsicsPolymorphicPriority.kt");
    }

    @Test
    @TestMetadata("intrinsicsStarProjections.kt")
    public void testIntrinsicsStarProjections() {
      run("intrinsicsStarProjections.kt");
    }

    @Test
    @TestMetadata("KeepGeneratedSerializer.kt")
    public void testKeepGeneratedSerializer() {
      run("KeepGeneratedSerializer.kt");
    }

    @Test
    @TestMetadata("localSerializable.kt")
    public void testLocalSerializable() {
      run("localSerializable.kt");
    }

    @Test
    @TestMetadata("metaSerializable.kt")
    public void testMetaSerializable() {
      run("metaSerializable.kt");
    }

    @Test
    @TestMetadata("mpp.kt")
    public void testMpp() {
      run("mpp.kt");
    }

    @Test
    @TestMetadata("mppInheritance.kt")
    public void testMppInheritance() {
      run("mppInheritance.kt");
    }

    @Test
    @TestMetadata("multiFieldValueClasses.kt")
    public void testMultiFieldValueClasses() {
      run("multiFieldValueClasses.kt");
    }

    @Test
    @TestMetadata("multiFileInheritanceJs.kt")
    public void testMultiFileInheritanceJs() {
      run("multiFileInheritanceJs.kt");
    }

    @Test
    @TestMetadata("multimoduleInheritance.kt")
    public void testMultimoduleInheritance() {
      run("multimoduleInheritance.kt");
    }

    @Test
    @TestMetadata("multimoduleInheritanceJs.kt")
    public void testMultimoduleInheritanceJs() {
      run("multimoduleInheritanceJs.kt");
    }

    @Test
    @TestMetadata("multimoduleInheritanceJsGeneric.kt")
    public void testMultimoduleInheritanceJsGeneric() {
      run("multimoduleInheritanceJsGeneric.kt");
    }

    @Test
    @TestMetadata("multipleGenericsPolymorphic.kt")
    public void testMultipleGenericsPolymorphic() {
      run("multipleGenericsPolymorphic.kt");
    }

    @Test
    @TestMetadata("namedCompanions.kt")
    public void testNamedCompanions() {
      run("namedCompanions.kt");
    }

    @Test
    @TestMetadata("polymorphic.kt")
    public void testPolymorphic() {
      run("polymorphic.kt");
    }

    @Test
    @TestMetadata("polymorphicTypeParameter.kt")
    public void testPolymorphicTypeParameter() {
      run("polymorphicTypeParameter.kt");
    }

    @Test
    @TestMetadata("privateCustomSerializer.kt")
    public void testPrivateCustomSerializer() {
      run("privateCustomSerializer.kt");
    }

    @Test
    @TestMetadata("repeatableSerialInfo.kt")
    public void testRepeatableSerialInfo() {
      run("repeatableSerialInfo.kt");
    }

    @Test
    @TestMetadata("sealedClassMultifile.kt")
    public void testSealedClassMultifile() {
      run("sealedClassMultifile.kt");
    }

    @Test
    @TestMetadata("sealedInterfaces.kt")
    public void testSealedInterfaces() {
      run("sealedInterfaces.kt");
    }

    @Test
    @TestMetadata("serialInfo.kt")
    public void testSerialInfo() {
      run("serialInfo.kt");
    }

    @Test
    @TestMetadata("serializableCompanion.kt")
    public void testSerializableCompanion() {
      run("serializableCompanion.kt");
    }

    @Test
    @TestMetadata("serializableFromAnotherModule.kt")
    public void testSerializableFromAnotherModule() {
      run("serializableFromAnotherModule.kt");
    }

    @Test
    @TestMetadata("serializableFromAnotherModule_multipleFields.kt")
    public void testSerializableFromAnotherModule_multipleFields() {
      run("serializableFromAnotherModule_multipleFields.kt");
    }

    @Test
    @TestMetadata("serializableOnPropertyType.kt")
    public void testSerializableOnPropertyType() {
      run("serializableOnPropertyType.kt");
    }

    @Test
    @TestMetadata("serializerFactory.kt")
    public void testSerializerFactory() {
      run("serializerFactory.kt");
    }

    @Test
    @TestMetadata("serializerFactoryInUserDefined.kt")
    public void testSerializerFactoryInUserDefined() {
      run("serializerFactoryInUserDefined.kt");
    }

    @Test
    @TestMetadata("singleFileInheritanceJs.kt")
    public void testSingleFileInheritanceJs() {
      run("singleFileInheritanceJs.kt");
    }

    @Test
    @TestMetadata("starProjections.kt")
    public void testStarProjections() {
      run("starProjections.kt");
    }

    @Test
    @TestMetadata("starProjectionsSealed.kt")
    public void testStarProjectionsSealed() {
      run("starProjectionsSealed.kt");
    }

    @Test
    @TestMetadata("suspendLambdaInDefault.kt")
    public void testSuspendLambdaInDefault() {
      run("suspendLambdaInDefault.kt");
    }

    @Test
    @TestMetadata("typealiasesInContextualTest.kt")
    public void testTypealiasesInContextualTest() {
      run("typealiasesInContextualTest.kt");
    }

    @Test
    @TestMetadata("typealiasesTest.kt")
    public void testTypealiasesTest() {
      run("typealiasesTest.kt");
    }

    @Test
    @TestMetadata("useSerializersChain.kt")
    public void testUseSerializersChain() {
      run("useSerializersChain.kt");
    }

    @Test
    @TestMetadata("userDefinedSerializerInCompanion.kt")
    public void testUserDefinedSerializerInCompanion() {
      run("userDefinedSerializerInCompanion.kt");
    }

    @Test
    @TestMetadata("uuidSerializer.kt")
    public void testUuidSerializer() {
      run("uuidSerializer.kt");
    }
  }

  @Nested
  @TestMetadata("plugins/kotlinx-serialization/testData/codegen")
  @TestDataPath("$PROJECT_ROOT")
  public class Codegen {
    private void run(String fileName) {
      runTest("plugins/kotlinx-serialization/testData/codegen/" + fileName);
    }

    @Test
    public void testAllFilesPresentInCodegen() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("plugins/kotlinx-serialization/testData/codegen"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("Basic.kt")
    public void testBasic() {
      run("Basic.kt");
    }

    @Test
    @TestMetadata("Intrinsics.kt")
    public void testIntrinsics() {
      run("Intrinsics.kt");
    }

    @Test
    @TestMetadata("IntrinsicsAdvanced.kt")
    public void testIntrinsicsAdvanced() {
      run("IntrinsicsAdvanced.kt");
    }

    @Test
    @TestMetadata("IntrinsicsNonReified.kt")
    public void testIntrinsicsNonReified() {
      run("IntrinsicsNonReified.kt");
    }

    @Test
    @TestMetadata("KeepGeneratedSerializer.kt")
    public void testKeepGeneratedSerializer() {
      run("KeepGeneratedSerializer.kt");
    }

    @Test
    @TestMetadata("Sealed.kt")
    public void testSealed() {
      run("Sealed.kt");
    }
  }
}
