{
    "formatVersion": "1.1",
    "component": {
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-annotations-common",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.0.0"
        }
    },
    "variants": [
        {
            "name": "legacyElements",
            "attributes": {
                "org.gradle.category": "library"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ]
        }
    ]
}