{
    "formatVersion": "1.1",
    "component": {
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-gradle-plugin",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.7.1"
        }
    },
    "variants": [
        {
            "name": "apiElementsWithFixedAttribute",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "fus-statistics-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-ArtifactsTest.version.jar",
                    "url": "kotlin-gradle-plugin-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "gradle96ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "9.6"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "fus-statistics-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-ArtifactsTest.version-gradle96.jar",
                    "url": "kotlin-gradle-plugin-ArtifactsTest.version-gradle96.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle96JavadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "9.6"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-ArtifactsTest.version-gradle96-javadoc.jar",
                    "url": "kotlin-gradle-plugin-ArtifactsTest.version-gradle96-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle96RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.gradle.plugin.api-version": "9.6"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "fus-statistics-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-statistics",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-compiler-runner",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-compiler-embeddable"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-idea",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-idea-proto",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-klib-commonizer-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-util-klib-metadata",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-ArtifactsTest.version-gradle96.jar",
                    "url": "kotlin-gradle-plugin-ArtifactsTest.version-gradle96.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "gradle96SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.plugin.api-version": "9.6"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-ArtifactsTest.version-gradle96-sources.jar",
                    "url": "kotlin-gradle-plugin-ArtifactsTest.version-gradle96-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-gradle-plugin",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "javadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-ArtifactsTest.version-javadoc.jar",
                    "url": "kotlin-gradle-plugin-ArtifactsTest.version-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "runtimeElementsWithFixedAttribute",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "fus-statistics-gradle-plugin",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-build-statistics",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-compiler-runner",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-compiler-embeddable"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-idea",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugin-idea-proto",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-gradle-plugins-bom",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "attributes": {
                        "org.gradle.category": "platform"
                    },
                    "endorseStrictVersions": true,
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-klib-commonizer-api",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-util-klib-metadata",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    },
                    "excludes": [
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-reflect"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-script-runtime"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-common"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk7"
                        },
                        {
                            "group": "org.jetbrains.kotlin",
                            "module": "kotlin-stdlib-jdk8"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "kotlin-gradle-plugin-ArtifactsTest.version.jar",
                    "url": "kotlin-gradle-plugin-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "sourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "kotlin-gradle-plugin-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-gradle-plugin-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        }
    ]
}
