/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.compiler.plugins;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugins.TestGeneratorKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("plugins/plugins-interactions-testing/testData/cli")
@TestDataPath("$PROJECT_ROOT")
public class PluginCliTestsGenerated extends AbstractPluginCliTests {
  private void run(String fileName) {
    doJvmTest("plugins/plugins-interactions-testing/testData/cli/" + fileName);
  }

  @Test
  public void testAllFilesPresentInCli() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("plugins/plugins-interactions-testing/testData/cli"), Pattern.compile("^(.+)\\.args$"), null, false);
  }

  @Test
  @TestMetadata("pluginsLegacyOrdered.args")
  public void testPluginsLegacyOrdered() {
    run("pluginsLegacyOrdered.args");
  }

  @Test
  @TestMetadata("pluginsLegacyReversed.args")
  public void testPluginsLegacyReversed() {
    run("pluginsLegacyReversed.args");
  }

  @Test
  @TestMetadata("pluginsLegacySorted.args")
  public void testPluginsLegacySorted() {
    run("pluginsLegacySorted.args");
  }

  @Test
  @TestMetadata("pluginsOrdered.args")
  public void testPluginsOrdered() {
    run("pluginsOrdered.args");
  }

  @Test
  @TestMetadata("pluginsReversed.args")
  public void testPluginsReversed() {
    run("pluginsReversed.args");
  }

  @Test
  @TestMetadata("pluginsSorted.args")
  public void testPluginsSorted() {
    run("pluginsSorted.args");
  }
}
