{
    "formatVersion": "1.1",
    "component": {
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-gradle-statistics",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.0.0"
        }
    },
    "variants": [
        {
            "name": "apiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "files": [
                {
                    "name": "kotlin-gradle-statistics-ArtifactsTest.version.jar",
                    "url": "kotlin-gradle-statistics-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "javadocElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "javadoc",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "kotlin-gradle-statistics-ArtifactsTest.version-javadoc.jar",
                    "url": "kotlin-gradle-statistics-ArtifactsTest.version-javadoc.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "runtimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.jvm.version": 8,
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "files": [
                {
                    "name": "kotlin-gradle-statistics-ArtifactsTest.version.jar",
                    "url": "kotlin-gradle-statistics-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "sourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "kotlin-gradle-statistics-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-gradle-statistics-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        }
    ]
}