{
    "formatVersion": "1.1",
    "component": {
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "8.14"
        }
    },
    "variants": [
        {
            "name": "jsApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.klib.packaging": "packed",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "available-at": {
                "url": "../../kotlin-test-js/ArtifactsTest.version/kotlin-test-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jsRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.klib.packaging": "packed",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "available-at": {
                "url": "../../kotlin-test-js/ArtifactsTest.version/kotlin-test-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jsSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "available-at": {
                "url": "../../kotlin-test-js/ArtifactsTest.version/kotlin-test-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "jvmApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "dependencyConstraints": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test-annotations-common",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test-common",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-test-ArtifactsTest.version.jar",
                    "url": "kotlin-test-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "jvmJUnit5ApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-junit5/ArtifactsTest.version/kotlin-test-junit5-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-junit5",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-junit5",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmJUnit5RuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-junit5/ArtifactsTest.version/kotlin-test-junit5-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-junit5",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-junit5",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmJUnit5SourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-junit5/ArtifactsTest.version/kotlin-test-junit5-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-junit5",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-junit5",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmJUnitApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-junit/ArtifactsTest.version/kotlin-test-junit-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-junit",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-junit",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmJUnitRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-junit/ArtifactsTest.version/kotlin-test-junit-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-junit",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-junit",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmJUnitSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-junit/ArtifactsTest.version/kotlin-test-junit-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-junit",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-junit",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "dependencyConstraints": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test-annotations-common",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test-common",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-test-ArtifactsTest.version.jar",
                    "url": "kotlin-test-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "jvmSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "files": [
                {
                    "name": "kotlin-test-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-test-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "jvmTestNGApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-testng/ArtifactsTest.version/kotlin-test-testng-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-testng",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-testng",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmTestNGRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-testng/ArtifactsTest.version/kotlin-test-testng-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-testng",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-testng",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmTestNGSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "available-at": {
                "url": "../../kotlin-test-testng/ArtifactsTest.version/kotlin-test-testng-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-testng",
                "version": "ArtifactsTest.version"
            },
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-testng",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "metadataApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-metadata",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "common"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "dependencyConstraints": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test-annotations-common",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test-common",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-test-ArtifactsTest.version-all.jar",
                    "url": "kotlin-test-ArtifactsTest.version-all.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-junit",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-junit5",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-testng",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "nativeApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "native"
            },
            "dependencyConstraints": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test-annotations-common",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test-common",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ]
        },
        {
            "name": "wasmJsApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.klib.packaging": "packed",
                "org.jetbrains.kotlin.wasm.target": "js"
            },
            "available-at": {
                "url": "../../kotlin-test-wasm-js/ArtifactsTest.version/kotlin-test-wasm-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-wasm-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmJsRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.klib.packaging": "packed",
                "org.jetbrains.kotlin.wasm.target": "js"
            },
            "available-at": {
                "url": "../../kotlin-test-wasm-js/ArtifactsTest.version/kotlin-test-wasm-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-wasm-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmJsSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "js"
            },
            "available-at": {
                "url": "../../kotlin-test-wasm-js/ArtifactsTest.version/kotlin-test-wasm-js-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-wasm-js",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmWasiApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.klib.packaging": "packed",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "available-at": {
                "url": "../../kotlin-test-wasm-wasi/ArtifactsTest.version/kotlin-test-wasm-wasi-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-wasm-wasi",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmWasiRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.klib.packaging": "packed",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "available-at": {
                "url": "../../kotlin-test-wasm-wasi/ArtifactsTest.version/kotlin-test-wasm-wasi-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-wasm-wasi",
                "version": "ArtifactsTest.version"
            }
        },
        {
            "name": "wasmWasiSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "wasm",
                "org.jetbrains.kotlin.wasm.target": "wasi"
            },
            "available-at": {
                "url": "../../kotlin-test-wasm-wasi/ArtifactsTest.version/kotlin-test-wasm-wasi-ArtifactsTest.version.module",
                "group": "org.jetbrains.kotlin",
                "module": "kotlin-test-wasm-wasi",
                "version": "ArtifactsTest.version"
            }
        }
    ]
}
