{
    "formatVersion": "1.1",
    "component": {
        "url": "../../kotlin-test/ArtifactsTest.version/kotlin-test-ArtifactsTest.version.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.2.1"
        }
    },
    "variants": [
        {
            "name": "jvmTestNGApiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-api",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.testng",
                    "module": "testng",
                    "version": {
                        "requires": "7.0.0"
                    }
                },
                {
                    "group": "org.testng",
                    "module": "testng",
                    "version": {
                        "requires": "7.5.1"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-test-testng-ArtifactsTest.version.jar",
                    "url": "kotlin-test-testng-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-impl",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-testng",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmTestNGRuntimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-test",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                },
                {
                    "group": "org.testng",
                    "module": "testng",
                    "version": {
                        "requires": "7.0.0"
                    }
                }
            ],
            "files": [
                {
                    "name": "kotlin-test-testng-ArtifactsTest.version.jar",
                    "url": "kotlin-test-testng-ArtifactsTest.version.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-impl",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-testng",
                    "version": "ArtifactsTest.version"
                }
            ]
        },
        {
            "name": "jvmTestNGSourcesElements",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime",
                "org.gradle.jvm.environment": "standard-jvm",
                "org.gradle.libraryelements": "jar",
                "org.jetbrains.kotlin.platform.type": "jvm"
            },
            "files": [
                {
                    "name": "kotlin-test-testng-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-test-testng-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ],
            "capabilities": [
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-framework-impl",
                    "version": "ArtifactsTest.version"
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "name": "kotlin-test-testng",
                    "version": "ArtifactsTest.version"
                }
            ]
        }
    ]
}