{
    "formatVersion": "1.1",
    "component": {
        "url": "../../kotlin-parcelize-runtime/ArtifactsTest.version/kotlin-parcelize-runtime-ArtifactsTest.version.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-parcelize-runtime",
        "version": "ArtifactsTest.version",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "9.6.1"
        }
    },
    "variants": [
        {
            "name": "jsApiElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-api",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "parcelize-runtime-js-ArtifactsTest.version.klib",
                    "url": "kotlin-parcelize-runtime-js-ArtifactsTest.version.klib",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "jsRuntimeElements-published",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "dependencies": [
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "ArtifactsTest.version"
                    }
                }
            ],
            "files": [
                {
                    "name": "parcelize-runtime-js-ArtifactsTest.version.klib",
                    "url": "kotlin-parcelize-runtime-js-ArtifactsTest.version.klib",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        },
        {
            "name": "jsSourcesElements-published",
            "attributes": {
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "kotlin-runtime",
                "org.gradle.jvm.environment": "non-jvm",
                "org.jetbrains.kotlin.platform.type": "js",
                "org.jetbrains.kotlin.js.compiler": "ir"
            },
            "files": [
                {
                    "name": "parcelize-runtime-js-ArtifactsTest.version-sources.jar",
                    "url": "kotlin-parcelize-runtime-js-ArtifactsTest.version-sources.jar",
                    "size": null,
                    "sha512": null,
                    "sha256": null,
                    "sha1": null,
                    "md5": null
                }
            ]
        }
    ]
}