// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// IGNORE_BACKEND: JVM_IR
// IGNORE_BACKEND_FIR: JVM_IR
// KJS_WITH_FULL_RUNTIME
// WITH_RUNTIME
import kotlin.test.*

fun box(): String {
    assertFailsWith<IllegalArgumentException> {
        val uintProgression = 1u until 8u
        for (i in uintProgression step -1) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        val ulongProgression = 1uL until 8uL
        for (i in ulongProgression step -1L) {
        }
    }

    return "OK"
}