/*
 * Copyright 2010-2019 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.backend.common.serialization.nextgen

val typeMappings = mapOf(
    "DescriptorReference" to "DeclarationDescriptor",
    "UniqId" to "UniqId",
    "Coordinates" to "Pair<Int, Int>",
    "Visibility" to "Visibility",
    "IrStatementOrigin" to "IrStatementOrigin",
    "KnownOrigin" to "IrDeclarationOrigin",
    "IrDataIndex" to "Int",
    "FqName" to "FqName",
    "IrDeclarationContainer" to "List<IrDeclaration>",
    "FileEntry" to "SourceManager.FileEntry",
    "IrFile" to "IrFile",
    "StringTable" to "Array<String>",
    "IrSymbolKind" to "Int",
    "IrSymbolData" to "IrSymbol",
    "IrSymbolTable" to "Array<IrSymbol>",
    "IrTypeVariance" to "Variance",
    "Annotations" to "List<IrConstructorCall>",
    "TypeArguments" to "List<IrTypeArgument>",
    "IrStarProjection" to "IrStarProjection",
    "IrTypeProjection" to "IrTypeProjection",
    "IrTypeArgument" to "IrTypeArgument",
    "IrSimpleType" to "IrSimpleType",
    "IrTypeAbbreviation" to "IrTypeAbbreviation",
    "IrDynamicType" to "IrDynamicType",
    "IrErrorType" to "IrErrorType",
    "IrType" to "IrType",
    "IrTypeTable" to "Array<IrType>",
    "IrBreak" to "IrBreak",
    "IrBlock" to "IrBlock",
    "MemberAccessCommon" to "IrMemberAccessExpression",
    "IrCall" to "IrCall",
    "IrConstructorCall" to "IrConstructorCall",
    "IrFunctionReference" to "IrFunctionReference",
    "IrLocalDelegatedPropertyReference" to "IrLocalDelegatedPropertyReference",
    "IrPropertyReference" to "IrPropertyReference",
    "IrComposite" to "IrComposite",
    "IrClassReference" to "IrClassReference",
    "IrConst" to "IrConst",
    "IrContinue" to "IrContinue",
    "IrDelegatingConstructorCall" to "IrDelegatingConstructorCall",
    "IrDoWhile" to "IrDoWhile",
    "IrEnumConstructorCall" to "IrEnumConstructorCall",
    "IrGetClass" to "IrGetClass",
    "IrGetEnumValue" to "IrGetEnumValue",
    "FieldAccessCommon" to "IrFieldAccessExpression",
    "IrGetField" to "IrGetField",
    "IrGetValue" to "IrGetValue",
    "IrGetObject" to "IrGetObject",
    "IrInstanceInitializerCall" to "IrInstanceInitializerCall",
    "Loop" to "IrLoop",
    "IrReturn" to "IrReturn",
    "IrSetField" to "IrSetField",
    "IrSetVariable" to "IrSetVariable",
    "IrSpreadElement" to "IrSpreadElement",
    "IrStringConcat" to "IrStringConcat",
    "IrThrow" to "IrThrow",
    "IrTry" to "IrTry",
    "IrTypeOp" to "IrTypeOperatorCall",
    "IrVararg" to "IrVararg",
    "IrVarargElement" to "IrVarargElement",
    "IrWhen" to "IrWhen",
    "IrWhile" to "IrWhile",
    "IrFunctionExpression" to "IrFunctionExpression",
    "IrDynamicMemberExpression" to "IrDynamicMemberExpression",
    "IrDynamicOperator" to "IrDynamicOperator",
    "IrDynamicOperatorExpression" to "IrDynamicOperatorExpression",
    "IrOperation" to "IrExpression",
    "IrTypeOperator" to "IrTypeOperator",
    "IrExpression" to "IrExpression",
    "NullableIrExpression" to "IrExpression",
    "IrDeclarationBase" to "IrDeclaration",
    "IrFunctionBase" to "IrFunction",
    "IrFunction" to "IrSimpleFunction",
    "IrConstructor" to "IrConstructor",
    "IrField" to "IrField",
    "IrLocalDelegatedProperty" to "IrLocalDelegatedProperty",
    "IrProperty" to "IrProperty",
    "IrVariable" to "IrVariable",
    "ClassKind" to "ClassKind",
    "ModalityKind" to "Modality",
    "IrValueParameter" to "IrValueParameter",
    "IrTypeParameter" to "IrTypeParameter",
    "IrTypeParameterContainer" to "IrTypeParameterContainer",
    "IrClass" to "IrClass",
    "IrTypeAlias" to "IrTypeAlias",
    "IrEnumEntry" to "IrEnumEntry",
    "IrAnonymousInit" to "IrAnonymousInitializer",
    "IrDeclaration" to "IrDeclaration",
    "IrBranch" to "IrBranch",
    "IrBlockBody" to "IrBlockBody",
    "IrCatch" to "IrCatch",
    "IrSyntheticBodyKind" to "IrSyntheticBodyKind",
    "IrSyntheticBody" to "IrSyntheticBodyKind",
    "IrStatement" to "IrStatement"
)
