// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: compiler/ir/serialization.common/src/KotlinIr.proto
// Protobuf Java Version: 4.29.3

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrVarargOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 element_type = 1 [features = { ... }</code>
   * @return Whether the elementType field is set.
   */
  boolean hasElementType();
  /**
   * <code>int32 element_type = 1 [features = { ... }</code>
   * @return The elementType.
   */
  int getElementType();

  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
   */
  java.util.List<org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement> 
      getElementList();
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement getElement(int index);
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
   */
  int getElementCount();
}