edition = "2023";

package org.jetbrains.kotlin.importmodels.proto;
option java_multiple_files = true;

import "google/protobuf/any.proto";

enum ErrorType {
  ERROR_TYPE_UNSPECIFIED = 0;
  ERROR_TYPE_UNKNOWN_MODEL_ID = 1;
  ERROR_TYPE_UNKNOWN_MODEL_PARAMS = 2;
  ERROR_TYPE_UNSUPPORTED_MODEL_ID = 3;
  ERROR_TYPE_UNSUPPORTED_MODEL_PARAMS = 4;
  ERROR_TYPE_INTERNAL_ERROR = 5;
  ERROR_TYPE_GENERIC_ERROR = 6;
}

message Error {
  ErrorType error_type = 1;
  string error_message = 2;
}

message Result {
  oneof result {
    google.protobuf.Any model = 1;
    Error error = 2;
  }
}

message Version {
  uint32 major = 1;
  uint32 minor = 2;
  uint32 patch = 3;
  string classifier = 4;
}

enum Capability {
  CAPABILITY_UNSPECIFIED = 0;
  CAPABILITY_JVM = 1;
  CAPABILITY_KAPT = 2;
}

enum Platform {
  PLATFORM_UNSPECIFIED = 0;
  PLATFORM_JVM = 1;
}

enum SourceRootKind {
  SOURCE_ROOT_KIND_UNSPECIFIED = 0;
  SOURCE_ROOT_KIND_SOURCE = 1;
  SOURCE_ROOT_KIND_GENERATED = 2;
}

message SourceRoot {
  string path = 1;
  SourceRootKind kind = 2;
  repeated Action producing_actions = 3;
}

message CompilationUnitId {
  string value = 1;
}

message BaseModel {
  string id = 1;
  Version plugin_version = 2;
  repeated Capability capabilities = 3;
}

message ProjectModel {
  string id = 1;
  repeated CompilationUnitId compilation_unit_ids = 3;
}

message Action {
  oneof build_tool_action {
    GradleTaskAction gradle_action = 1;
  }
}

message GradleTaskAction {
  string task_path = 1;
}

message CompilationUnitModel {
  message Parameters {
    CompilationUnitId compilation_unit_id = 1;
  }

  string id = 1;
  Parameters parameters = 2;
  string compilation_name = 3;
  Platform platform = 4;
  bool is_test = 5;
  repeated Action build_actions = 6;
  repeated SourceRoot source_roots = 7;
}
