(module
    (func $print_i32 (import "spectest" "print_i32") (param i32))
    
    (func (export "fd_write") (param i32 i32 i32 i32) (result i32)
        (i32.const 701)
        (call $print_i32)
        (i32.const 11)
        (unreachable)
    )
    (func (export "random_get") (param i32 i32) (result i32)
        (i32.const 702)
        (call $print_i32)
        (unreachable)
    )
    ;;???
    (func (export "args_get") (param i32 i32) (result i32)
        (i32.const 703)
        (call $print_i32)
        (unreachable)
    )
    (func (export "args_sizes_get") (param i32 i32) (result i32)
        (i32.const 704)
        (call $print_i32)
        (unreachable)
    )
    ;;???
    (func (export "clock_time_get") (param i32 i64 i32) (result i32)
        (i32.const 705)
        (call $print_i32)
        (unreachable)
    )
    ;; test
    (func (export "proc_exit") (param i32)
        (i32.const 706)
        (call $print_i32)
        (unreachable)
    )
)
(register "wasi_snapshot_preview1")
(input "index.wasm")  
(module instance) 
(invoke "_initialize") 
(invoke "runBoxTest")
