package transitiveStory.midActual.sourceCalls.intemediateCall

import transitiveStory.bottomActual.mppBeginning.BottomActualDeclarations

actual class BottomActualMPPInheritor : BottomActualDeclarations()
