import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    id "org.jetbrains.kotlin.jvm"
}

repositories {
    mavenLocal()
    mavenCentral()
}

compileKotlin {
    compilerOptions {
        languageVersion = KotlinVersion.KOTLIN_2_4 // Latest stable minus 1.
        apiVersion = KotlinVersion.KOTLIN_2_4 // Latest stable minus 1.
    }
}
