{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlinx-atomicfu-runtime",
    "version": "ArtifactsTest.version",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-atomicfu-runtime-ArtifactsTest.version.klib",
          "url": "kotlinx-atomicfu-runtime-ArtifactsTest.version.klib",
          "size": null,
          "sha512": null,
          "sha256": null,
          "sha1": null,
          "md5": null
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-atomicfu-runtime-ArtifactsTest.version.klib",
          "url": "kotlinx-atomicfu-runtime-ArtifactsTest.version.klib",
          "size": null,
          "sha512": null,
          "sha256": null,
          "sha1": null,
          "md5": null
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-atomicfu-runtime-ArtifactsTest.version-sources.jar",
          "url": "kotlinx-atomicfu-runtime-ArtifactsTest.version-sources.jar",
          "size": null,
          "sha512": null,
          "sha256": null,
          "sha1": null,
          "md5": null
        }
      ]
    }
  ]
}
