{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uklib-maven-gradle-packaging/1.0/uklib-maven-gradle-packaging-1.0.module",
    "group": "foo.bar",
    "module": "uklib-maven-gradle-packaging",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
      ],
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-linuxX64Main-1.0.klib",
          "url": "uklib-maven-gradle-packaging-linuxx64-1.0.klib",
          "size": 2904,
          "sha512": "7620f3d94694935a0456fcf0734a6086791e413df0ccbf8fcba010a973e37fe1214f1b20e5073c75865ed4f4af59bff4652ce69b82d1a22ba32e49f735970f81",
          "sha256": "32f76351a64522285a7ea010d54c4e8c90f8e291a9aac92ae08b0d379a08944e",
          "sha1": "7f44a111456c6f17093d156be526e5777c166b43",
          "md5": "3a54e72010817e78d0b4e482a5f224a4"
        },
        {
          "name": "uklib-maven-gradle-packaging-linuxX64Cinterop-fooMain-1.0.klib",
          "url": "uklib-maven-gradle-packaging-linuxx64-1.0-cinterop-foo.klib",
          "size": 4527,
          "sha512": "4e3b1a7473056d5c649a7c6d6b5f930e2605faa16f280b83a54f727da974b6443f1757c5f8e4cbeaa6705c36be144a2ac983d3582abb95fde0061e28123ddb07",
          "sha256": "3f5a48d38e2b2bff3e4feacffea0ebf3e402d30f96e093b9e2f3f3f9ba4c815e",
          "sha1": "818e8abfe80d6046ab7062698c0f745ab1a2d019",
          "md5": "8859d1f5821dade3b4623fd9919739eb"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "uklib-maven-gradle-packaging-linuxx64-1.0-sources.jar",
          "url": "uklib-maven-gradle-packaging-linuxx64-1.0-sources.jar",
          "size": 479,
          "sha512": "686fd77f21ca2150e77e98fe3abb42871bc5ed26bb27e9be865c5aebe28bba09bb08dd4b1c5d127cce6b8d7eeefbfb64c86214ae3d332e7cfc70b32497358cd1",
          "sha256": "30af047fb16af81c8e78a5626ba0e0eb2d2afe7f7ea6bba0c823229bdfbdb0a2",
          "sha1": "2e05b1f02fbb2bbe1edd8e1d92a8912d2c0b6670",
          "md5": "f45f3fa2a7276ddd0cd618d7217d8884"
        }
      ]
    }
  ]
}
