/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.cli.metadata

import org.jetbrains.kotlin.incremental.components.ICFileMappingTracker
import org.jetbrains.kotlin.library.writer.KlibWrittenMetadataPackageFragmentTracker
import java.nio.file.Path

internal class ICMetadataMappingTracker(private val fileMappingTracker: ICFileMappingTracker) : KlibWrittenMetadataPackageFragmentTracker {

    /**
     * If [sourceFile] is present, the output is mapped to it. Otherwise, the fragment originates from a synthetic
     * file backing top-level declarations generated by a compiler plugin, so it has no real source owner and is
     * recorded as plugin-generated, which lets incremental compilation clean it up on every round.
     */
    override fun recordSourceFile(sourceFile: Path?, outputFile: Path) {
        if (sourceFile != null) {
            fileMappingTracker.recordSourceFilesToOutputFileMapping(listOf(sourceFile.toFile()), outputFile.toFile())
        } else {
            fileMappingTracker.recordOutputFileGeneratedForPlugin(outputFile.toFile())
        }
    }
}

internal fun ICFileMappingTracker.toICMetadataMappingTracker(): ICMetadataMappingTracker = ICMetadataMappingTracker(this)
