/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.config.keys.generator

import org.jetbrains.kotlin.backend.konan.AllocationMode
import org.jetbrains.kotlin.backend.konan.LlvmVariant
import org.jetbrains.kotlin.backend.konan.TestRunnerKind
import org.jetbrains.kotlin.config.keys.generator.model.KeysContainer
import org.jetbrains.kotlin.konan.target.CompilerOutputKind
import org.jetbrains.kotlin.konan.target.KonanTarget

@Suppress("unused")
object KonanConfigurationKeysContainer : KeysContainer("org.jetbrains.kotlin.backend.konan", "KonanConfigKeys") {
    val BUNDLE_ID by key<String>("bundle ID to be set in Info.plist of a produced framework")
    val CHECK_DEPENDENCIES by key<Boolean>("check dependencies and download the missing ones")
    val DEBUG by key<Boolean>("add debug information")
    val FAKE_OVERRIDE_VALIDATOR by key<Boolean>("fake override validator")
    val EMIT_LAZY_OBJC_HEADER_FILE by key<String>("output file to emit lazy Obj-C header")
    val ENABLE_ASSERTIONS by key<Boolean>("enable runtime assertions in generated code")
    val ENTRY by key<String>("fully qualified main() name")
    val EXPORTED_LIBRARIES by key<List<String>>("libraries included into produced framework API")
    val FULL_EXPORTED_NAME_PREFIX by key<String>("prefix used when exporting Kotlin names to other languages")
    val LIBRARY_TO_ADD_TO_CACHE by key<String>("path to library that to be added to cache")
    val CACHE_DIRECTORIES by key<List<String>>("paths to directories containing caches")
    val AUTO_CACHEABLE_FROM by key<List<String>>("paths to the root directories from which dependencies are to be cached automatically")
    val AUTO_CACHE_DIR by key<String>("path to the directory where to put caches for auto-cacheable dependencies")
    val INCREMENTAL_CACHE_DIR by key<String>("path to the directory where to put incremental build caches")
    val CACHED_LIBRARIES by key<Map<String, String>>("mapping from library paths to cache paths")
    val FILES_TO_CACHE by key<List<String>>("which files should be compiled to cache")
    val MAKE_PER_FILE_CACHE by key<Boolean>("make per-file cache")
    val FRAMEWORK_IMPORT_HEADERS by key<List<String>>("headers imported to framework header")
    val FRIEND_MODULES by key<List<String>>("friend module paths")
    val REFINES_MODULES by key<List<String>>("refines module paths")
    val GENERATE_TEST_RUNNER by key<TestRunnerKind>("generate test runner")
    val INCLUDED_BINARY_FILES by key<List<String>>("included binary file paths")
    val KONAN_HOME by key<String>("overridden compiler distribution path")
    val LIBRARY_FILES by key<List<String>>("library file paths")
    val LIGHT_DEBUG by key<Boolean>("add light debug information")
    val GENERATE_DEBUG_TRAMPOLINE by key<Boolean>("generates debug trampolines to make debugger breakpoint resolution more accurate")
    val LINKER_ARGS by key<List<String>>("additional linker arguments")
    val LIST_TARGETS by key<Boolean>("list available targets")
    val MANIFEST_FILE by key<String>("provide manifest addend file")
    val HEADER_KLIB by key<String>("path to file where header klib should be produced")
    val MODULE_NAME by key<String>("module name")
    val NATIVE_LIBRARY_FILES by key<List<String>>("native library file paths")
    val NODEFAULTLIBS by key<Boolean>("don't link with the default libraries")
    val NOENDORSEDLIBS by key<Boolean>("don't link with the endorsed libraries")
    val NOMAIN by key<Boolean>("assume 'main' entry point to be provided by external libraries")
    val NOSTDLIB by key<Boolean>("don't link with stdlib")
    val NOPACK by key<Boolean>("don't the library into a klib file")
    val OPTIMIZATION by key<Boolean>("optimized compilation")
    val OUTPUT by key<String>("program or library name")
    val OVERRIDE_CLANG_OPTIONS by key<List<String>>("arguments for clang")
    val ALLOCATION_MODE by key<AllocationMode>("allocation mode")
    val EXPORT_KDOC by key<Boolean>("export KDoc into klib and framework")
    val PRINT_BITCODE by key<Boolean>("print bitcode")
    val PRINT_IR by key<Boolean>("print ir")
    val PRINT_FILES by key<Boolean>("print files")
    val PRODUCE by key<CompilerOutputKind>("compiler output kind")
    val PURGE_USER_LIBS by key<Boolean>("purge user-specified libs too")
    val RUNTIME_FILE by key<String>("override default runtime file path")
    val INCLUDED_LIBRARIES by key<List<String>>("klibs processed in the same manner as source files")
    val SHORT_MODULE_NAME by key<String>("short module name for IDE and export")
    val STATIC_FRAMEWORK by key<Boolean>("produce a static library for a framework")
    val TARGET by key<String>("target we compile for")
    val TEMPORARY_FILES_DIR by key<String>("directory for temporary files")
    val SAVE_LLVM_IR by key<List<String>>("save LLVM IR")
    val VERIFY_BITCODE by key<Boolean>("verify bitcode")
    val VERIFY_COMPILER by key<Boolean>("verify compiler")
    val WRITE_DEPENDENCIES_OF_PRODUCED_KLIB_TO by key<String>("write dependencies of the klib being produced to the given path")
    val DEBUG_INFO_VERSION by key<Int>("debug info format version")
    val OBJC_GENERICS by key<Boolean>("write objc header with generics support")
    val DEBUG_PREFIX_MAP by key<Map<String, String>>("remap file source paths in debug info")
    val PRE_LINK_CACHES by key<Boolean>("perform compiler caches pre-link")
    val OVERRIDE_KONAN_PROPERTIES by key<Map<String, String>>("override konan.properties values")
    val PROPERTY_LAZY_INITIALIZATION by key<Boolean>("lazy top level properties initialization")
    val EXTERNAL_DEPENDENCIES by key<String>("use external dependencies to enhance IR linker error messages")
    val LLVM_VARIANT by key<LlvmVariant>("llvm variant")
    val RUNTIME_LOGS by key<String>("enable runtime logging")
    val TEST_DUMP_OUTPUT_PATH by key<String>("path to a file to dump the list of all available tests")
    val OMIT_FRAMEWORK_BINARY by key<Boolean>("do not generate binary in framework")
    val COMPILE_FROM_BITCODE by key<String>("path to bitcode file to compile")
    val SERIALIZED_DEPENDENCIES by key<String>("path to serialized dependencies for native linking")
    val SAVE_DEPENDENCIES_PATH by key<String>("path to save serialized dependencies to")
    val SAVE_LLVM_IR_DIRECTORY by key<String>("directory to store LLVM IR from phases")
    val KONAN_DATA_DIR by key<String>("directory for storing konan dependencies, cache and prebuilds")
    val MANIFEST_NATIVE_TARGETS by key<List<KonanTarget>>("value of native_targets property to write in manifest")
    val LLVM_MODULE_PASSES by key<String>("llvm passes to run instead of module optimization pipeline")
    val LLVM_LTO_PASSES by key<String>("llvm passes to run instead of LTO optimization pipeline")
}
