/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.config.keys.generator

import org.jetbrains.kotlin.backend.konan.AllocationMode
import org.jetbrains.kotlin.backend.konan.LlvmVariant
import org.jetbrains.kotlin.backend.konan.TestRunnerKind
import org.jetbrains.kotlin.config.keys.generator.model.KeysContainer
import org.jetbrains.kotlin.konan.target.CompilerOutputKind
import org.jetbrains.kotlin.konan.target.KonanTarget

@Suppress("unused")
object NativeConfigurationKeysContainer : KeysContainer("org.jetbrains.kotlin.konan.config", "NativeConfigurationKeys") {
    val BUNDLE_ID by key<String>("Bundle ID to be set in Info.plist of a produced framework.")
    val CHECK_DEPENDENCIES by key<Boolean>("Check dependencies and download the missing ones.")
    val DEBUG by key<Boolean>()
    val FAKE_OVERRIDE_VALIDATOR by key<Boolean>()
    val EMIT_LAZY_OBJC_HEADER_FILE by key<String>()
    val ENABLE_ASSERTIONS by key<Boolean>()
    val KONAN_ENTRY_POINT by key<String>("Fully qualified main() name.")
    val EXPORTED_LIBRARIES by key<List<String>>("Libraries included into produced framework API.")
    val FULL_EXPORTED_NAME_PREFIX by key<String>("Prefix used when exporting Kotlin names to other languages.")
    val KONAN_LIBRARY_TO_ADD_TO_CACHE by key<String>()
    val CACHE_DIRECTORIES by key<List<String>>()
    val AUTO_CACHEABLE_FROM by key<List<String>>("Paths to the root directories from which dependencies are to be cached automatically.")
    val AUTO_CACHE_DIR by key<String>("Path to the directory where to put caches for auto-cacheable dependencies.")
    val INCREMENTAL_CACHE_DIR by key<String>("Path to the directory where to put incremental build caches.")
    val CACHED_LIBRARIES by key<Map<String, String>>("Mapping from library paths to cache paths.")
    val FILES_TO_CACHE by key<List<String>>("Which files should be compiled to cache.")
    val MAKE_PER_FILE_CACHE by key<Boolean>()
    val FRAMEWORK_IMPORT_HEADERS by key<List<String>>()
    val KONAN_FRIEND_LIBRARIES by key<List<String>>()
    val KONAN_REFINES_MODULES by key<List<String>>()
    val GENERATE_TEST_RUNNER by key<TestRunnerKind>()
    val KONAN_INCLUDED_BINARIES by key<List<String>>()
    val KONAN_HOME by key<String>()
    val KONAN_LIBRARIES by key<List<String>>()
    val LIGHT_DEBUG by key<Boolean>()
    val GENERATE_DEBUG_TRAMPOLINE by key<Boolean>("Generates debug trampolines to make debugger breakpoint resolution more accurate.")
    val LINKER_ARGS by key<List<String>>()
    val LIST_TARGETS by key<Boolean>()
    val KONAN_MANIFEST_ADDEND by key<String>()
    val KONAN_GENERATED_HEADER_KLIB_PATH by key<String>("Path to file where header klib should be produced.")
    val KONAN_NATIVE_LIBRARIES by key<List<String>>()
    val KONAN_NO_DEFAULT_LIBS by key<Boolean>("Don't link with the default libraries.")
    val KONAN_NO_ENDORSED_LIBS by key<Boolean>("Don't link with the endorsed libraries.")
    val NOMAIN by key<Boolean>("Assume 'main' entry point to be provided by external libraries.")
    val KONAN_NO_STDLIB by key<Boolean>("Don't link with stdlib.")
    val KONAN_DONT_COMPRESS_KLIB by key<Boolean>("Don't pack the library into a klib file.")
    val OPTIMIZATION by key<Boolean>()
    val KONAN_OUTPUT_PATH by key<String>()
    val OVERRIDE_CLANG_OPTIONS by key<List<String>>()
    val ALLOCATION_MODE by key<AllocationMode>()
    val KONAN_EXPORT_KDOC by key<Boolean>("Export KDoc into klib and framework.")
    val KONAN_PRINT_BITCODE by key<Boolean>()
    val KONAN_PRINT_IR by key<Boolean>()
    val KONAN_PRINT_FILES by key<Boolean>()
    val KONAN_PRODUCED_ARTIFACT_KIND by key<CompilerOutputKind>()
    val KONAN_PURGE_USER_LIBS by key<Boolean>()
    val RUNTIME_FILE by key<String>()
    val KONAN_INCLUDED_LIBRARIES by key<List<String>>("Klibs processed in the same manner as source files.")
    val KONAN_SHORT_MODULE_NAME by key<String>("Short module name for IDE and export.")
    val STATIC_FRAMEWORK by key<Boolean>("Produce a static library for a framework.")
    val KONAN_TARGET by key<String>()
    val TEMPORARY_FILES_DIR by key<String>()
    val SAVE_LLVM_IR by key<List<String>>()
    val VERIFY_BITCODE by key<Boolean>()
    val VERIFY_COMPILER by key<Boolean>()
    val KONAN_WRITE_DEPENDENCIES_OF_PRODUCED_KLIB_TO by key<String>()
    val DEBUG_INFO_VERSION by key<Int>()
    val OBJC_GENERICS by key<Boolean>("Write objc header with generics support.")
    val DEBUG_PREFIX_MAP by key<Map<String, String>>("Remap file source paths in debug info.")
    val PRE_LINK_CACHES by key<Boolean>("Perform compiler caches pre-link.")
    val OVERRIDE_KONAN_PROPERTIES by key<Map<String, String>>("Override konan.properties values.")
    val PROPERTY_LAZY_INITIALIZATION by key<Boolean>()
    val EXTERNAL_DEPENDENCIES by key<String>("Use external dependencies to enhance IR linker error messages.")
    val LLVM_VARIANT by key<LlvmVariant>()
    val RUNTIME_LOGS by key<String>()
    val TEST_DUMP_OUTPUT_PATH by key<String>("Path to a file to dump the list of all available tests.")
    val OMIT_FRAMEWORK_BINARY by key<Boolean>("Do not generate binary in framework.")
    val COMPILE_FROM_BITCODE by key<String>("Path to bitcode file to compile.")
    val SERIALIZED_DEPENDENCIES by key<String>("Path to serialized dependencies for native linking.")
    val SAVE_DEPENDENCIES_PATH by key<String>("Path to save serialized dependencies to.")
    val SAVE_LLVM_IR_DIRECTORY by key<String>("Directory to store LLVM IR from phases.")
    val KONAN_DATA_DIR by key<String>("Directory for storing konan dependencies, cache and prebuilds.")
    val KONAN_MANIFEST_NATIVE_TARGETS by key<List<KonanTarget>>("Value of native_targets property to write in manifest.")
    val LLVM_MODULE_PASSES by key<String>("LLVM passes to run instead of module optimization pipeline.")
    val LLVM_LTO_PASSES by key<String>("LLVM passes to run instead of LTO optimization pipeline.")
}
