org.jetbrains.kotlin.buildtools.api.arguments.enums.AbiStabilityMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.AnnotationDefaultTargetMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.AssertionsMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.CompatqualAnnotationsMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.ExplicitApiMode=2.3.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.HeaderMode=2.3.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.JdkRelease=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.JspecifyAnnotationsMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.JvmDefaultMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.JvmTarget=2.3.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.KotlinVersion=2.3.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.LambdasMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.NameBasedDestructuringMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.ReturnValueCheckerMode=2.3.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.SamConversionsMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.StringConcatMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.VerifyIrMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.enums.WhenExpressionsMode=2.4.0
org.jetbrains.kotlin.buildtools.api.arguments.types.ProfileCompilerCommand=2.4.0
